name: Build and Push Docker Image for Java App

on:
  workflow_call:
    secrets:
      GCP_SA_REGISTRY_MANAGER_CREDENTIALS:
        required: true
      GCP_PROJECT_ENUBE:
        required: true
    inputs:
      IMAGE_NAME:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_SA_REGISTRY_MANAGER_CREDENTIALS }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: "${{ secrets.GCP_PROJECT }}"

      - name: "Use gcloud CLI"
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGISTRY_ZONE }}-docker.pkg.dev

      - name: Set image tags
        run: |
          TIMESTAMP=$(date -u +'%Y%m%d-%H%M%S')
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}" | tr '/' '-')
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-8)
          echo "IMAGE_TAG=${BRANCH_NAME}-${SHORT_SHA}-${TIMESTAMP}" >> $GITHUB_ENV
          echo "IMAGE_PATH=${{ secrets.GCP_REGISTRY_ZONE }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ vars.REGISTRY }}/${{ inputs.IMAGE_NAME }}" >> $GITHUB_ENV


      - name: Build Docker images
        run: |
          echo "Building image with tags:"
          echo "Docker image name generated: ${{env.IMAGE_PATH}}:${{ env.IMAGE_TAG }}"
          docker build -t ${{env.IMAGE_PATH}}:${{ env.IMAGE_TAG }} 
            

      - name: List Docker images
        run: |
          echo "Available images:"
          docker images | grep ${{ inputs.IMAGE_NAME }}

      - name: Push Docker images
        run: |
          echo "Pushing image with tags:"          
          echo "Pushing image with name: ${{env.IMAGE_PATH}}:${{ env.IMAGE_TAG }}"
          docker push ${{env.IMAGE_PATH}}:${{ env.IMAGE_TAG }}